import mongoose from "mongoose";

const customOrderSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  customerName: String,
  email: String,
  phone: String,
  designer: String,
  productName: String,
  description: String,
  blouseType: String,
  neckType: String,
  sleeveType: String,
  backDesign: String,
  fitType: String,
  fabricType: String,
  color: String,
  lining: String,
  padding: String,
  hookZipPlacement: String,
  bustSize: String,
  underBust: String,
  waistSize: String,
  shoulderSize: String,
  armHole: String,
  sleeveLength: String,
  frontNeckDepth: String,
  backNeckDepth: String,
  blouseLength: String,
  chestToApex: String,
  notes: String,
  occasion: String,
  extraNotes: String,
  price: String,
  urgencyLevel: String,
  deliveryDate: String,
  referenceImage: String,
  fabricImage: String,
  neckDesignImage: String,
  sleeveDesignImage: String,
  inspirationImage: String,
}, { timestamps: true });

export default mongoose.model("CustomOrder", customOrderSchema);
